### ISSUE TITLE
Create a bid auction action that can be called from frontend

### ISSUE THREAD

**Issue by carlosero** [sublimeconcept/tupuja-backend#4]
Tasks:

- [x] Should increase the amount of bids of the auction by 1
- [x] Should update time by 1 min.
- [x] Should increase the curren price by 1 cent.
- [x] Should decrease user's credit.
- [x] Should pass tests.

**Comment by cantwait** [comment]
In progress

**Comment by cantwait** [comment]
Issue completed... nonetheless I don't like the performance.... need to check the behavior with the code deployed on firebase...
